#!/bin/bash
#To be executed from the top directory of the repository
#The static binary is compiled in a Dockerfile and then copied into the main file
rm -f loat-static
docker build -t loat .
docker create -ti --name loat_dummy loat bash
docker cp loat_dummy:/src/LoAT/build/static/release/loat-static ./loat-static
docker rm -f loat_dummy
