#!/bin/bash
#To be executed from the top directory of the repository
#The static binary is compiled in a Dockerfile and then copied into the main file
SHA=$(git rev-parse HEAD)
git diff-index --quiet HEAD --
DIRTY=$?
docker build -t loat --build-arg SHA=$SHA --build-arg DIRTY=$DIRTY .
docker create -ti --name loat_dummy loat bash
mkdir -p ./build/static/release
docker cp loat_dummy:/src/LoAT/build/static/release/loat-static ./build/static/release/loat-static
docker rm -f loat_dummy
